info:
  app:
    name: backend
    description: Backend service for JAAKD

spring:
  application:
    name: backend

  autoconfigure:
    exclude: ## remove after adding the datasource configuration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration

  #datasource:
  #  url: ${DATABASE_URL}
  #  username: ${DATABASE_USERNAME}
  #  password: ${DATABASE_PASSWORD}

server:
    port: 8080

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always